import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from '@/app/components/Navbar'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const localBusinessSchema = {
  "@context": "https://schema.org",
  "@type": "AutoRepair",
  "name": "Discount Auto Smog & Tire",
  "image": "https://www.discountautosmogoakland.com/og-image.jpg", // update once hosted
  "url": "https://www.discountautosmogoakland.com",
  "telephone": "+15106552729",
  "priceRange": "$$",
  "address": {
    "@type": "PostalAddress",
    "streetAddress": "5443 Shattuck Ave",
    "addressLocality": "Oakland",
    "addressRegion": "CA",
    "postalCode": "94609",
    "addressCountry": "US"
  },
  "geo": {
    "@type": "GeoCoordinates",
    "latitude": 37.838421,
    "longitude": -122.261942
  },
  "openingHoursSpecification": [
    {
      "@type": "OpeningHoursSpecification",
      "dayOfWeek": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
      "opens": "08:30",
      "closes": "17:30"
    },
    {
      "@type": "OpeningHoursSpecification",
      "dayOfWeek": "Saturday",
      "opens": "08:30",
      "closes": "16:00"
    }
  ]
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className="bg-slate-950 text-slate-100 antialiased">
        
        {/* Persistent Global Header */}
        <Navbar />

        {/* Dynamic Page Content */}
        <main>{children}</main>

        {/* Global Footer schema can go down here */}
      </body>
    </html>
  );
}